version: "3"

tasks:
  migrate:
    desc: "apply migrations"
    cmds:
      - go run cmd/migrator/main.go
  run:
    desc: "run server"
    cmds:
      - go run cmd/app/main.go
  compose-up:
    desc: "run docker compose"
    cmds:
      - docker-compose up -d
  compose-down:
    desc: "stop docker compose"
    cmds:
      - docker-compose down
  swagger:
    desc: "generate swagger docs"
    cmds:
      - swag fmt
      - swag init -g ./cmd/app/main.go -o cmd/docs --parseDependency --parseInternal